clone_depth: 1

install:
    # Remove dependencies that prevent us from upgrading to GCC 6.2
    - C:\msys64\usr\bin\bash -lc "pacman -Rs --noconfirm mingw-w64-x86_64-gcc-ada mingw-w64-x86_64-gcc-fortran mingw-w64-x86_64-gcc-libgfortran mingw-w64-x86_64-gcc-objc"

    # Update to GCC 6.2 and install dependencies
    - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -Sy mingw-w64-x86_64-gcc mingw-w64-x86_64-qt5 mingw-w64-x86_64-libusb mingw-w64-x86_64-boost mingw-w64-x86_64-python3 mingw-w64-x86_64-fftw mingw-w64-x86_64-libzip mingw-w64-x86_64-glibmm mingw-w64-x86_64-ninja"

    # Install pre-compiled libraries
    - appveyor DownloadFile http://swdownloads.analog.com/cse/build/msys64.tar.xz -FileName C:\msys64.tar.xz
    - C:\msys64\usr\bin\bash -lc "cd /c ; tar xJf msys64.tar.xz"

    # Hack: Qt5Qml CMake script throws errors when loading its plugins. So let's just drop those plugins.
    - C:\msys64\usr\bin\bash -lc "rm -f /mingw64/lib/cmake/Qt5Qml/*Factory.cmake"

build_script:
    - set PATH=C:\msys64\mingw64\bin;%PATH%
    - C:\msys64\usr\bin\bash -lc "mkdir /c/build ; cd /c/build ; cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DPKG_CONFIG_EXECUTABLE=/mingw64/bin/pkg-config.exe -DCMAKE_C_COMPILER=x86_64-w64-mingw32-gcc.exe -DCMAKE_CXX_COMPILER=x86_64-w64-mingw32-g++.exe /c/projects/scopy && ninja"
    - appveyor PushArtifact c:\build\scopy.exe
